# configures the server + db connection

spring.application.name=hospital-api
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=michellely
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver